### ISSUE TITLE
Could you publish a release relying on curator 4.0.0

### ISSUE THREAD

**Issue by gregsilin** [sclasen/akka-zk-cluster-seed#34]
Running the latest version of this library with curator 4.0.0, zookeeper 3.5.3 gives us the following:

```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.curator.framework.api.CreateBuilder.creatingParentsIfNeeded()Lorg/apache/curator/framework/api/ProtectACLCreateModePathAndBytesable;
    at akka.cluster.seed.ZookeeperClusterSeed.$anonfun$createPathIfNeeded$1(ZookeeperClusterSeed.scala:212)
    at scala.Option.getOrElse(Option.scala:121)
    at akka.cluster.seed.ZookeeperClusterSeed.createPathIfNeeded(ZookeeperClusterSeed.scala:211)
    at akka.cluster.seed.ZookeeperClusterSeed.join(ZookeeperClusterSeed.scala:151)
```

I traced it down to the fact that the return type of the `creatingParentsIfNeeded` signature changed from `ProtectACLCreateModePathAndBytesable<String>` to `ProtectACLCreateModeStatPathAndBytesable<String>` in curator 4.0.0.  

I also see that the interface definition moved up from `CreateBuilder` to `CreateBuilderMain` but don't think that should be the issue, since the implementing class has to implement the method regardless.

If it's possible to publish a release with the new version of curator that'd be a great help, I'm happy to open a PR.

**Comment by sclasen** [comment]
sure, a PR would be great, thanks!

**Comment by gregsilin** [comment]
Done, thanks

https://github.com/sclasen/akka-zk-cluster-seed/pull/35

Not sure what sort of pre-release quality gates you have for releasing.
